id: IB8BB4B98
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T11:11:23+00:00'
last_modified: '2022-06-15T16:52:35.984235+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21888
  title: གཏེར་ཆོས། ཀུན་བཟང་བདེ་སྐྱོང་དབང་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E20D:
      image_group_id: I1983
      title: ''
      total_pages: 517
      order: 1
      base_file: E20D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
